# baseURL = "/"
# deploying on github
basURL = "https://iani.github.io/compmus-class" # 1
publishDir = "docs" # 2
languageCode = "en-US"
defaultContentLanguage = "en"



title = "Μουσική Πληροφορική"
theme = "hugo-theme-learn"
# themesdir = "../.."
# metaDataFormat = "toml" # THE PREVIOUS IS NO LONGER NEEDED
# changing ox-hugo export to yaml via:
# (defcustom org-hugo-front-matter-format "toml"
#   "Format used to front matter.
# This variable can be set to either \"toml\" or \"yaml\"."
#   :group 'org-export-hugo
#   :type '(choice
#           (const :tag "TOML" "toml")
#           (const :tag "YAML" "yaml")))
# Need therefore to set org-hugo-front-matter-format to "yaml"
# Note: "yaml" with small letters - but NOT "YAML". 

defaultContentLanguageInSubdir= true

[params]
#  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Μουσική Πληροφορική"
  author = "Γιάννης Ζάννος"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Μουσική Πληροφορική"
weight = 1
languageName = "Ελληνικά"

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fab fa-fw fa-github'></i> Github repo"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-camera'></i> Showcases"
# url = "showcase"
# weight = 11

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30

# [Languages.fr]
# title = "Documentation du thème Hugo Learn"
# weight = 2
# languageName = "Français"

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fab fa-fw fa-github'></i> Repo Github"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
# url = "/showcase"
# weight = 11

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
# url = "/credits"
# weight = 30
